
server:
  port: 8090

spring:
  datasource:
    name: hypergraph
    url: jdbc:mysql://localhost:3306/hypergraph?allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
